title: Projects
subtitle: All the projects by the team and community
# Define immediate project order below, everything else will be sorted by created date
# Sorting is checked against your name field on the project file - make sure it matches!
projects:
  - WolvenKit
  - CP77 Tools
communityProjects:
